name: Recent Activity

on:
  schedule:
    - cron: '*/5 * * * *' # Update every 5 minutes
  workflow_dispatch:

jobs:
  build:
    name: Update Profile README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Recent Activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: "recent-activity.config.yml"
