name: Recent Activity

on:
  schedule:
    - cron: '*/30 * * * *' # Update every 30 minutes
  workflow_dispatch:

jobs:
  build:
    name: Update Profile README
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Recent Activity
        uses: Readme-Workflows/recent-activity@{version}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: "recent-activity.yml"
